language: node_js

node_js:
  - node

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN_PORTFOLIO
  keep_history: true
  local_dir: dist
  on:
    branch: master
